name: 
  test-and-deploy-application
on:
#  push:
#    branches:
#      - 'main'
#    paths-ignore:
#      - '.github/workflows'
#  issues:
#    types:
#      - opened
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches: 
      - 'main'
    paths-ignore:
      - '.github/workflows'
  workflow_dispatch:    
jobs:
  test-app:
    runs-on: 
      ubuntu-24.04
    steps:
      - name: 
          Pull Codebase
        uses: 
          actions/checkout@v4
      - name: 
          Install NodeJS
        uses: 
          actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: 
          Install Dependencies
        run: 
          npm ci
      - name: 
          Lint Codebase
        run: npm run lint
      - name: 
          Test Codebase
        run: 
          npm test
  deploy-app:
# needs keyword is required to run 2 jobs sequentially. By default the jobs run in parallel.
    needs: 
      [test-app]
    runs-on: 
      ubuntu-24.04
    steps:
      - name: 
          Pull Codebase
        uses: 
          actions/checkout@v4
      - name: 
          Install NodeJS
        uses: 
          actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: 
          Install Dependencies
        run: 
          npm ci
      - name: 
          Deploy Codebase
        run: 
          echo "Build deployed!!!"